BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libphantom_vm.a pvm_test

SRCDIRS += $(BUILD_ROOT)/vm $(BUILD_ROOT)/vm/resources $(BUILD_ROOT)/vm/video

INCDIRS += /usr/include/w32api/

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/vm/makerules
