BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libphantom_user.a pmod_test

SRCDIRS += $(BUILD_ROOT)/user

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/user/makerules
