goal::
	@echo Usage: make {test,clean}

test::
	sh RunUnitTests.sh 

        
clean::
	-rm *.class
	-rm *.realOutput 
	-rm test/pc/*.pc
	-rm test/pc/*.lstc
	-rm test/pc/*.lst
	-rm test/pc/*.d
