#include <mach/asm.h>
#include "SYS.h"

//SYSCALL(getpagesize)

//SYSCALL(personality)



SYSCALL(gettid)
SYSCALL(getpid) 
SYSCALL(getuid)
SYSCALL(getuid32)
SYSCALL(getpgid) 
SYSCALL(getpgrp) 
SYSCALL(getppid) 
SYSCALL(getegid) 
SYSCALL(getegid32)
SYSCALL(geteuid) 
SYSCALL(geteuid32) 
SYSCALL(getgid) 
SYSCALL(getgid32)



SYSCALL(setgid)
SYSCALL(setgid32)
SYSCALL(setgroups)
SYSCALL(setgroups32)
SYSCALL(setpgid)
SYSCALL(setregid)
SYSCALL(setregid32)
SYSCALL(setresgid)
SYSCALL(setresgid32)
SYSCALL(setresuid)
SYSCALL(setresuid32)
SYSCALL(setreuid)
SYSCALL(setreuid32)
SYSCALL(setuid)
SYSCALL(setuid32)
SYSCALL(setpgrp) 

