BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libphantom_user.a

SRCDIRS += $(BUILD_ROOT)/user $(BUILD_ROOT)/user/$(ARCH)

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/user/makerules
