MYNAME=newos

BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= lib$(MYNAME).a

SRCDIRS += $(BUILD_ROOT)/$(MYNAME)

#INCDIRS += ../kernel

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/$(MYNAME)/makerules
