BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= sh

SRCDIRS += $(BUILD_ROOT)/modules/shell

include $(BUILD_ROOT)/makerules-usr

include $(BUILD_ROOT)/modules/shell/makerules

analyse::
	#
