RESDIR=$(PHANTOM_HOME)/plib/resources/buttons
#CONV=java -cp $(PHANTOM_HOME)/build/jar/plc.jar ru.dz.pbitmap.Main

#vpath %.png $(RESDIR)

#%.png.c: %.png
#	$(CONV) $<

all::  #close.png.c pin.png.c close_pressed.png.c
	cp $(RESDIR)/*.c .
