BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libtmalloc.a

SRCDIRS += $(BUILD_ROOT)/tmalloc 
#$(BUILD_ROOT)/tmalloc/$(ARCH)

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/tmalloc/makerules
