BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= pmod_test

SRCDIRS += $(BUILD_ROOT)/modules/test

include $(BUILD_ROOT)/makerules-usr

include $(BUILD_ROOT)/modules/test/makerules

analyse::
	#
