goal:: src/ru/dz/plc/CompileDate.java


src/ru/dz/plc/CompileDate.java::
	echo 'package ru.dz.plc;' >$@
	echo 'class CompileDate {' >>$@
	echo 'static String getDate() { return "' `date` '"; }' >>$@
	echo '};' >>$@

