package ru.dz.pfsck;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/** 
   A strongly-typed resource class, for looking up localized strings, etc.
 
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
* /
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{

	private static System.Resources.ResourceManager resourceMan;

	private static System.Globalization.CultureInfo resourceCulture;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public Resources()
	{
	}

	 
	   // Returns the cached ResourceManager instance used by this class.
	 
	
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Resources.ResourceManager getResourceManager()
	{
		if ((resourceMan == null))
		{
			System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PhantomFileSystemChecker.Properties.Resources", Resources.class.getPackage());
			resourceMan = temp;
		}
		return resourceMan;
	}

	   // Overrides the current thread's CurrentUICulture property for all
	   // resource lookups using this strongly typed resource class.
	 
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Globalization.CultureInfo getCulture()
	{
		return resourceCulture;
	}
	public static void setCulture(System.Globalization.CultureInfo value)
	{
		resourceCulture = value;
	}
}

*/
