BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libthreads.a

SRCDIRS += $(BUILD_ROOT)/threads $(BUILD_ROOT)/threads/$(ARCH)

#INCDIRS += /usr/include/w32api/

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/threads/makerules
