
PHANTOM_SRCDIR	= ..
OBJDIR		= ..

prefix		= /usr/local
exec_prefix	= ${prefix}

include $(OBJDIR)/Makeconf

##### End of configuration section #####

#include $(PHANTOM_SRCDIR)/machdep/$(HOST_ARCH)/GNUmakerules
include $(PHANTOM_SRCDIR)/phantom/GNUmakerules
