all::
	$(MAKE) -C roots all
	$(MAKE) -C sys all
#	$(MAKE) -C apps all

clean::
	$(MAKE) -C sys clean
	$(MAKE) -C sys clean
#	$(MAKE) -C apps clean
	-rm bin/*.c bin/*.ll bin/*.pc bin/*.lst bin/*.lstc bin/*.d bin/*.java
