
PHANTOM_SRCDIR	= $(realpath $(PHANTOM_HOME))/oldtree/kernel
OBJDIR		= ..

prefix		= /usr/local
exec_prefix	= ${prefix}

include $(realpath $(PHANTOM_HOME))/config.mk
include $(OBJDIR)/Makeconf-$(ARCH)

##### End of configuration section #####

include $(PHANTOM_SRCDIR)/phantom/GNUmakerules
