BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libphantom.a 

SRCDIRS += $(BUILD_ROOT)/libphantom $(BUILD_ROOT)/libphantom/udis86 

INCDIRS += ../kernel

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/libphantom/makerules
