BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libphantom.a 

SRCDIRS += $(BUILD_ROOT)/libphantom

#INCDIRS += /usr/include/w32api/

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/libphantom/makerules
