BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libdev.a 

SRCDIRS += $(BUILD_ROOT)/dev $(BUILD_ROOT)/dev/ac97 
#$(BUILD_ROOT)/dev/ataio

INCDIRS += ../kernel

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/dev/makerules
