BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libdev.a 

SRCDIRS += $(BUILD_ROOT)/dev

INCDIRS += ../kernel

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/dev/makerules
