package ru.dz.pfsck;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
public final class Settings extends System.Configuration.ApplicationSettingsBase
{

	private static Settings defaultInstance = ((Settings)(System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

	public static Settings getDefault()
	{
		return defaultInstance;
	}



	private static Settings defaultInstance = ((Settings)(System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

	public static Settings getDefault()
	{
		return defaultInstance;
	}
}

*/
