BUILD_ROOT = $(realpath $(PHANTOM_HOME))/phantom

TARGET	= libfreetype.a

SRCDIRS += $(BUILD_ROOT)/libfreetype 
#$(BUILD_ROOT)/libfreetype/$(ARCH) 

include $(BUILD_ROOT)/makerules-lib

include $(BUILD_ROOT)/libfreetype/makerules
